"""HTML report export. Self-contained, no external assets."""
from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path

from .engine import ScanReport
from .issue import Severity, human_bytes

_CSS = """
:root{--bg:#12161c;--panel:#1a2029;--line:#2a3340;--text:#e6ebf2;--dim:#93a0b1;
--accent:#c9a227;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);
font:15px/1.6 "Segoe UI",system-ui,sans-serif;padding:32px}
.wrap{max-width:900px;margin:0 auto}
h1{font-size:26px;margin:0 0 4px;letter-spacing:.3px}
.sub{color:var(--dim);font-size:13px;margin-bottom:28px}
.score{display:flex;align-items:center;gap:22px;background:var(--panel);
border:1px solid var(--line);border-radius:14px;padding:22px 26px;margin-bottom:28px}
.num{font-size:52px;font-weight:600;line-height:1}
.verdict{font-size:16px}
.meta{color:var(--dim);font-size:13px;margin-top:6px}
h2{font-size:17px;margin:30px 0 10px;padding-bottom:8px;
border-bottom:1px solid var(--line)}
.issue{background:var(--panel);border:1px solid var(--line);border-left-width:4px;
border-radius:9px;padding:14px 16px;margin-bottom:10px}
.t{font-weight:600;margin-bottom:5px}
.d{color:var(--dim);font-size:13.5px;white-space:pre-wrap}
.tag{display:inline-block;font-size:11px;font-weight:600;letter-spacing:.5px;
text-transform:uppercase;padding:2px 8px;border-radius:20px;margin-right:8px}
.hint{margin-top:9px;font-size:13px;color:var(--accent)}
footer{margin-top:40px;color:var(--dim);font-size:12px;
border-top:1px solid var(--line);padding-top:16px}
"""


def render_html(report: ScanReport, app_name: str = "Auroch") -> str:
    score = report.health_score()
    if score >= 85:
        score_color = "#4fae6a"
    elif score >= 60:
        score_color = "#d0a03f"
    else:
        score_color = "#d0453f"

    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>{app_name} system report</title>",
        f"<style>{_CSS}</style></head><body><div class='wrap'>",
        f"<h1>{app_name} system report</h1>",
        f"<div class='sub'>{datetime.now().strftime('%A %d %B %Y, %H:%M')} &middot; "
        f"scan took {report.duration_s:.0f}s &middot; "
        f"{'elevated' if report.was_admin else 'standard user'}"
        f"{' &middot; deep scan' if report.deep else ''}</div>",
        "<div class='score'>",
        f"<div class='num' style='color:{score_color}'>{score}</div>",
        "<div><div class='verdict'>" + html.escape(report.verdict()) + "</div>",
        f"<div class='meta'>{len(report.problems)} issue(s) worth acting on &middot; "
        f"{human_bytes(report.reclaimable_bytes)} reclaimable</div></div></div>",
    ]

    for category, issues in report.by_category().items():
        parts.append(f"<h2>{html.escape(category)}</h2>")
        for issue in issues:
            parts.append(
                f"<div class='issue' style='border-left-color:{issue.severity.color}'>"
                f"<div class='t'>"
                f"<span class='tag' style='background:{issue.severity.color}22;"
                f"color:{issue.severity.color}'>{issue.severity.label}</span>"
                f"{html.escape(issue.title)}</div>"
                f"<div class='d'>{html.escape(issue.detail)}</div>"
                + (
                    f"<div class='hint'>→ {html.escape(issue.remediation_hint)}</div>"
                    if issue.remediation_hint
                    else ""
                )
                + "</div>"
            )

    if report.errors:
        parts.append("<h2>Scanners that failed</h2>")
        for name, error in report.errors.items():
            parts.append(
                f"<div class='issue' style='border-left-color:#6b7684'>"
                f"<div class='t'>{html.escape(name)}</div>"
                f"<div class='d'>{html.escape(error)}</div></div>"
            )

    parts.append(
        "<footer>Generated by " + app_name + ". Severity ratings are deliberately "
        "conservative: temporary files and orphaned registry entries are listed as "
        "Minor because that is what they are. Nothing in this report was changed "
        "on your system.</footer>"
    )
    parts.append("</div></body></html>")
    return "".join(parts)


def save_html(report: ScanReport, path: Path, app_name: str = "Auroch") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html(report, app_name), encoding="utf-8")
    return path
